Resources:
  ApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: api-gateway-authorizer-${self:custom.stage}
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      ProviderARNs:
        - Fn::GetAtt: [CognitoUserPool, Arn]
      RestApiId:
        Ref: ApiGatewayRestApi
